// Code generated by entc, DO NOT EDIT.

package post

import (
	"github.com/zjl233/gotter/ent/schema"
)

const (
	// Label holds the string label denoting the post type in the database.
	Label = "post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContent holds the string denoting the content vertex property in the database.
	FieldContent = "content"

	// Table holds the table name of the post in the database.
	Table = "posts"
)

// Columns holds all SQL columns for post fields.
var Columns = []string{
	FieldID,
	FieldContent,
}

var (
	fields = schema.Post{}.Fields()

	// descContent is the schema descriptor for content field.
	descContent = fields[0].Descriptor()
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator = func() func(string) error {
		validators := descContent.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(content string) error {
			for _, fn := range fns {
				if err := fn(content); err != nil {
					return err
				}
			}
			return nil
		}
	}()
)
