// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/zjl233/gotter/ent/authtoken"
	"github.com/zjl233/gotter/ent/predicate"
	"github.com/zjl233/gotter/ent/user"
)

// AuthTokenQuery is the builder for querying AuthToken entities.
type AuthTokenQuery struct {
	config
	limit      *int
	offset     *int
	order      []Order
	unique     []string
	predicates []predicate.AuthToken
	// eager-loading edges.
	withUser *UserQuery
	withFKs  bool
	// intermediate query.
	sql *sql.Selector
}

// Where adds a new predicate for the builder.
func (atq *AuthTokenQuery) Where(ps ...predicate.AuthToken) *AuthTokenQuery {
	atq.predicates = append(atq.predicates, ps...)
	return atq
}

// Limit adds a limit step to the query.
func (atq *AuthTokenQuery) Limit(limit int) *AuthTokenQuery {
	atq.limit = &limit
	return atq
}

// Offset adds an offset step to the query.
func (atq *AuthTokenQuery) Offset(offset int) *AuthTokenQuery {
	atq.offset = &offset
	return atq
}

// Order adds an order step to the query.
func (atq *AuthTokenQuery) Order(o ...Order) *AuthTokenQuery {
	atq.order = append(atq.order, o...)
	return atq
}

// QueryUser chains the current query on the user edge.
func (atq *AuthTokenQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: atq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(authtoken.Table, authtoken.FieldID, atq.sqlQuery()),
		sqlgraph.To(user.Table, user.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, authtoken.UserTable, authtoken.UserColumn),
	)
	query.sql = sqlgraph.SetNeighbors(atq.driver.Dialect(), step)
	return query
}

// First returns the first AuthToken entity in the query. Returns *NotFoundError when no authtoken was found.
func (atq *AuthTokenQuery) First(ctx context.Context) (*AuthToken, error) {
	ats, err := atq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(ats) == 0 {
		return nil, &NotFoundError{authtoken.Label}
	}
	return ats[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (atq *AuthTokenQuery) FirstX(ctx context.Context) *AuthToken {
	at, err := atq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return at
}

// FirstID returns the first AuthToken id in the query. Returns *NotFoundError when no id was found.
func (atq *AuthTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = atq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{authtoken.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (atq *AuthTokenQuery) FirstXID(ctx context.Context) int {
	id, err := atq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only AuthToken entity in the query, returns an error if not exactly one entity was returned.
func (atq *AuthTokenQuery) Only(ctx context.Context) (*AuthToken, error) {
	ats, err := atq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(ats) {
	case 1:
		return ats[0], nil
	case 0:
		return nil, &NotFoundError{authtoken.Label}
	default:
		return nil, &NotSingularError{authtoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (atq *AuthTokenQuery) OnlyX(ctx context.Context) *AuthToken {
	at, err := atq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return at
}

// OnlyID returns the only AuthToken id in the query, returns an error if not exactly one id was returned.
func (atq *AuthTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = atq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{authtoken.Label}
	default:
		err = &NotSingularError{authtoken.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (atq *AuthTokenQuery) OnlyXID(ctx context.Context) int {
	id, err := atq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuthTokens.
func (atq *AuthTokenQuery) All(ctx context.Context) ([]*AuthToken, error) {
	return atq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (atq *AuthTokenQuery) AllX(ctx context.Context) []*AuthToken {
	ats, err := atq.All(ctx)
	if err != nil {
		panic(err)
	}
	return ats
}

// IDs executes the query and returns a list of AuthToken ids.
func (atq *AuthTokenQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := atq.Select(authtoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (atq *AuthTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := atq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (atq *AuthTokenQuery) Count(ctx context.Context) (int, error) {
	return atq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (atq *AuthTokenQuery) CountX(ctx context.Context) int {
	count, err := atq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (atq *AuthTokenQuery) Exist(ctx context.Context) (bool, error) {
	return atq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (atq *AuthTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := atq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (atq *AuthTokenQuery) Clone() *AuthTokenQuery {
	return &AuthTokenQuery{
		config:     atq.config,
		limit:      atq.limit,
		offset:     atq.offset,
		order:      append([]Order{}, atq.order...),
		unique:     append([]string{}, atq.unique...),
		predicates: append([]predicate.AuthToken{}, atq.predicates...),
		// clone intermediate query.
		sql: atq.sql.Clone(),
	}
}

//  WithUser tells the query-builder to eager-loads the nodes that are connected to
// the "user" edge. The optional arguments used to configure the query builder of the edge.
func (atq *AuthTokenQuery) WithUser(opts ...func(*UserQuery)) *AuthTokenQuery {
	query := &UserQuery{config: atq.config}
	for _, opt := range opts {
		opt(query)
	}
	atq.withUser = query
	return atq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuthToken.Query().
//		GroupBy(authtoken.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (atq *AuthTokenQuery) GroupBy(field string, fields ...string) *AuthTokenGroupBy {
	group := &AuthTokenGroupBy{config: atq.config}
	group.fields = append([]string{field}, fields...)
	group.sql = atq.sqlQuery()
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AuthToken.Query().
//		Select(authtoken.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (atq *AuthTokenQuery) Select(field string, fields ...string) *AuthTokenSelect {
	selector := &AuthTokenSelect{config: atq.config}
	selector.fields = append([]string{field}, fields...)
	selector.sql = atq.sqlQuery()
	return selector
}

func (atq *AuthTokenQuery) sqlAll(ctx context.Context) ([]*AuthToken, error) {
	var (
		nodes       = []*AuthToken{}
		withFKs     = atq.withFKs
		_spec       = atq.querySpec()
		loadedTypes = [1]bool{
			atq.withUser != nil,
		}
	)
	if atq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, authtoken.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &AuthToken{config: atq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, atq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := atq.withUser; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*AuthToken)
		for i := range nodes {
			if fk := nodes[i].user_tokens; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_tokens" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	return nodes, nil
}

func (atq *AuthTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := atq.querySpec()
	return sqlgraph.CountNodes(ctx, atq.driver, _spec)
}

func (atq *AuthTokenQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := atq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (atq *AuthTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   authtoken.Table,
			Columns: authtoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authtoken.FieldID,
			},
		},
		From:   atq.sql,
		Unique: true,
	}
	if ps := atq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := atq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := atq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := atq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (atq *AuthTokenQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(atq.driver.Dialect())
	t1 := builder.Table(authtoken.Table)
	selector := builder.Select(t1.Columns(authtoken.Columns...)...).From(t1)
	if atq.sql != nil {
		selector = atq.sql
		selector.Select(selector.Columns(authtoken.Columns...)...)
	}
	for _, p := range atq.predicates {
		p(selector)
	}
	for _, p := range atq.order {
		p(selector)
	}
	if offset := atq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := atq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuthTokenGroupBy is the builder for group-by AuthToken entities.
type AuthTokenGroupBy struct {
	config
	fields []string
	fns    []Aggregate
	// intermediate query.
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the group-by query.
func (atgb *AuthTokenGroupBy) Aggregate(fns ...Aggregate) *AuthTokenGroupBy {
	atgb.fns = append(atgb.fns, fns...)
	return atgb
}

// Scan applies the group-by query and scan the result into the given value.
func (atgb *AuthTokenGroupBy) Scan(ctx context.Context, v interface{}) error {
	return atgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (atgb *AuthTokenGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := atgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (atgb *AuthTokenGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AuthTokenGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (atgb *AuthTokenGroupBy) StringsX(ctx context.Context) []string {
	v, err := atgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (atgb *AuthTokenGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AuthTokenGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (atgb *AuthTokenGroupBy) IntsX(ctx context.Context) []int {
	v, err := atgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (atgb *AuthTokenGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AuthTokenGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (atgb *AuthTokenGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := atgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (atgb *AuthTokenGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: AuthTokenGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (atgb *AuthTokenGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := atgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (atgb *AuthTokenGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := atgb.sqlQuery().Query()
	if err := atgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (atgb *AuthTokenGroupBy) sqlQuery() *sql.Selector {
	selector := atgb.sql
	columns := make([]string, 0, len(atgb.fields)+len(atgb.fns))
	columns = append(columns, atgb.fields...)
	for _, fn := range atgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(atgb.fields...)
}

// AuthTokenSelect is the builder for select fields of AuthToken entities.
type AuthTokenSelect struct {
	config
	fields []string
	// intermediate queries.
	sql *sql.Selector
}

// Scan applies the selector query and scan the result into the given value.
func (ats *AuthTokenSelect) Scan(ctx context.Context, v interface{}) error {
	return ats.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ats *AuthTokenSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ats.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (ats *AuthTokenSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AuthTokenSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ats *AuthTokenSelect) StringsX(ctx context.Context) []string {
	v, err := ats.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (ats *AuthTokenSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AuthTokenSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ats *AuthTokenSelect) IntsX(ctx context.Context) []int {
	v, err := ats.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (ats *AuthTokenSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AuthTokenSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ats *AuthTokenSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ats.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (ats *AuthTokenSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: AuthTokenSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ats *AuthTokenSelect) BoolsX(ctx context.Context) []bool {
	v, err := ats.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ats *AuthTokenSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ats.sqlQuery().Query()
	if err := ats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ats *AuthTokenSelect) sqlQuery() sql.Querier {
	selector := ats.sql
	selector.Select(selector.Columns(ats.fields...)...)
	return selector
}
