// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/zjl233/gotter/ent/authtoken"
	"github.com/zjl233/gotter/ent/predicate"
)

// AuthTokenDelete is the builder for deleting a AuthToken entity.
type AuthTokenDelete struct {
	config
	predicates []predicate.AuthToken
}

// Where adds a new predicate to the delete builder.
func (atd *AuthTokenDelete) Where(ps ...predicate.AuthToken) *AuthTokenDelete {
	atd.predicates = append(atd.predicates, ps...)
	return atd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (atd *AuthTokenDelete) Exec(ctx context.Context) (int, error) {
	return atd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (atd *AuthTokenDelete) ExecX(ctx context.Context) int {
	n, err := atd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (atd *AuthTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: authtoken.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authtoken.FieldID,
			},
		},
	}
	if ps := atd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, atd.driver, _spec)
}

// AuthTokenDeleteOne is the builder for deleting a single AuthToken entity.
type AuthTokenDeleteOne struct {
	atd *AuthTokenDelete
}

// Exec executes the deletion query.
func (atdo *AuthTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := atdo.atd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authtoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (atdo *AuthTokenDeleteOne) ExecX(ctx context.Context) {
	atdo.atd.ExecX(ctx)
}
