// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"log"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"

	"github.com/zjl233/gotter/ent/user"
)

// dsn for the database. In order to run the tests locally, run the following command:
//
//	 ENT_INTEGRATION_ENDPOINT="root:pass@tcp(localhost:3306)/test?parseTime=True" go test -v
//
var dsn string

func ExampleAuthToken() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the authtoken's edges.

	// create authtoken vertex with its edges.
	at := client.AuthToken.
		Create().
		SetCreatedAt(time.Now()).
		SetUpdatedAt(time.Now()).
		SetToken("string").
		SetExpiresAt(time.Now()).
		SaveX(ctx)
	log.Println("authtoken created:", at)

	// query edges.

	// Output:
}
func ExampleUser() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the user's edges.
	at0 := client.AuthToken.
		Create().
		SetCreatedAt(time.Now()).
		SetUpdatedAt(time.Now()).
		SetToken("string").
		SetExpiresAt(time.Now()).
		SaveX(ctx)
	log.Println("authtoken created:", at0)

	// create user vertex with its edges.
	u := client.User.
		Create().
		SetCreatedAt(time.Now()).
		SetUpdatedAt(time.Now()).
		SetUsername("string").
		SetPasswordHash("string").
		SetNickname("string").
		SetStatus(user.StatusActive).
		AddTokens(at0).
		SaveX(ctx)
	log.Println("user created:", u)

	// query edges.
	at0, err = u.QueryTokens().First(ctx)
	if err != nil {
		log.Fatalf("failed querying tokens: %v", err)
	}
	log.Println("tokens found:", at0)

	// Output:
}
