// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// NewUser defines model for NewUser.
type NewUser struct {

	// User name, Unique, cannot change
	Account string `json:"account"`

	// User's nickname
	Name string `json:"name"`

	// User password, at least 8 character
	Password string `json:"password"`

	// Must same as password
	Password2 string `json:"password2"`
}

// User defines model for User.
type User struct {

	// Unique id of the post
	Id         int    `json:"_id"`
	Account    string `json:"account"`
	BkgWallImg string `json:"bkgWallImg"`
	Follower   []int  `json:"follower"`
	Following  []int  `json:"following"`
	Name       string `json:"name"`
	Posts      []int  `json:"posts"`
	ProfileImg string `json:"profileImg"`
}

// XAuth defines model for x-auth.
type XAuth string

// Error defines model for Error.
type Error struct {
	Err map[string]interface{} `json:"err"`

	// Error message
	ErrMsg string `json:"errMsg"`
	Result bool   `json:"result"`
}

// SignUpJSONBody defines parameters for SignUp.
type SignUpJSONBody NewUser

// InfoParams defines parameters for Info.
type InfoParams struct {

	// jwt auth
	XAuth XAuth `json:"x-auth"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

// SignUpRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody SignUpJSONBody

// LoginRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody
