// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {

	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// NewPost defines model for NewPost.
type NewPost struct {

	// content of the post
	Content string `json:"content"`
}

// Post defines model for Post.
type Post struct {
	// Embedded struct due to allOf(#/components/schemas/NewPost)
	NewPost
	// Embedded fields due to inline allOf schema

	// Unique id of the post
	Id int64 `json:"id"`
}

// FindPostsParams defines parameters for FindPosts.
type FindPostsParams struct {

	// set first post to return
	Offset *int32 `json:"offset,omitempty"`

	// maximum number of results to return
	Limit *int32 `json:"limit,omitempty"`
}

// AddPostJSONBody defines parameters for AddPost.
type AddPostJSONBody NewPost

// AddPostRequestBody defines body for AddPost for application/json ContentType.
type AddPostJSONRequestBody AddPostJSONBody
