// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {

	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// NewPost defines model for NewPost.
type NewPost struct {

	// Content of the post
	Content string `json:"content"`
}

// NewUser defines model for NewUser.
type NewUser struct {

	// User password, at least 8 character
	Password string `json:"password"`

	// Must same as password
	PasswordConfirm string `json:"password_confirm"`

	// User name, Unique, cannot change
	Username string `json:"username"`
}

// Post defines model for Post.
type Post struct {
	// Embedded struct due to allOf(#/components/schemas/NewPost)
	NewPost
	// Embedded fields due to inline allOf schema

	// Unique id of the post
	Id int64 `json:"id"`
}

// User defines model for User.
type User struct {

	// Unique id of the post
	Id int32 `json:"id"`

	// Unique name of the user
	Username string `json:"username"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// SignUpJSONBody defines parameters for SignUp.
type SignUpJSONBody NewUser

// AuthTestParams defines parameters for AuthTest.
type AuthTestParams struct {

	// json web token
	XAuth string `json:"x-auth"`
}

// FindPostsParams defines parameters for FindPosts.
type FindPostsParams struct {

	// set first post to return
	Offset *int32 `json:"offset,omitempty"`

	// maximum number of results to return
	Limit *int32 `json:"limit,omitempty"`
}

// AddPostJSONBody defines parameters for AddPost.
type AddPostJSONBody NewPost

// LoginRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// SignUpRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody SignUpJSONBody

// AddPostRequestBody defines body for AddPost for application/json ContentType.
type AddPostJSONRequestBody AddPostJSONBody
