// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// AuthToken is the predicate function for authtoken builders.
type AuthToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
